name: sbb_data_scanner
description: Recognition of optical encoded information for SBB use cases.
repository: https://github.com/SchweizerischeBundesbahnen/data-scanner-flutter
issue_tracker: https://github.com/SchweizerischeBundesbahnen/data-scanner-flutter/issues
topics: [scanner]

version: 4.5.0

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/camera
  camera: ^0.11.0+2
  # https://pub.dev/packages/google_mlkit_text_recognition
  google_mlkit_text_recognition: 0.13.0
  # https://pub.dev/packages/google_mlkit_barcode_scanning
  google_mlkit_barcode_scanning: 0.12.0
  # https://pub.dev/packages/native_device_orientation
  native_device_orientation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/mocktail
  mocktail: ^1.0.4
